### ISSUE TITLE
Mouse scroll for volume change causing error.

### ISSUE THREAD

**Issue by Ookami313** [Silarn/volumizer#1]
Downloaded your fixed version of Volumizer (thanks by the way), and for the most part it looks like most things work, except if I put my cursor over the LDB element and try to use the scroll wheel on my mouse to change the volume setting I get the following error. Thanks.

2x Interface/AddOns/Volumizer/Volumizer.lua:938: attempt to call field 'BlizzardOptionsPanel_GetCVarSafe' (a nil value)
[string "@Interface/AddOns/Volumizer/Volumizer.lua"]:938: in function `OnMouseWheel'
[string "@Interface/AddOns/Bazooka/Bazooka.lua"]:1410: in function <Interface/AddOns/Bazooka/Bazooka.lua:1404>

Locals:
self = BazookaPlugin_Volumizer {
 0 = <userdata>
 bzkPlugin = <table> {
 }
}
delta = 1
ref = <table> {
 VolumeCVar = "Sound_MasterVolume"
 EnableCVar = "Sound_EnableAllSound"
 Tooltip = "Enables or disables all sound."
 SoundOption = <table> {
 }
}
(*temporary) = nil
(*temporary) = "Sound_MasterVolume"
(*temporary) = "attempt to call field 'BlizzardOptionsPanel_GetCVarSafe' (a nil value)"
VOLUMES = <table> {
 master = <table> {
 }
 music = <table> {
 }
 ambience = <table> {
 }
 sfx = <table> {
 }
}
math = <table> {
 log = <function> defined =[C]:-1
 acos = <function> defined =[C]:-1
 ldexp = <function> defined =[C]:-1
 huge = Infinite
 pi = 3.141593
 pow = <function> defined =[C]:-1
 tanh = <function> defined =[C]:-1
 deg = <function> defined =[C]:-1
 tan = <function> defined =[C]:-1
 cosh = <function> defined =[C]:-1
 cos = <function> defined =[C]:-1
 random = <function> defined =[C]:-1
 sinh = <function> defined =[C]:-1
 frexp = <function> defined =[C]:-1
 ceil = <function> defined =[C]:-1
 floor = <function> defined =[C]:-1
 rad = <function> defined =[C]:-1
 abs = <function> defined =[C]:-1
 sqrt = <function> defined =[C]:-1
 modf = <function> defined =[C]:-1
 asin = <function> defined =[C]:-1
 min = <function> defined =[C]:-1
 max = <function> defined =[C]:-1
 fmod = <function> defined =[C]:-1
 log10 = <function> defined =[C]:-1
 atan2 = <function> defined =[C]:-1
 exp = <function> defined =[C]:-1
 sin = <function> defined =[C]:-1
 atan = <function> defined =[C]:-1
}

**Comment by Silarn** [comment]
Interesting, I guess Titan panel doesn't support mouse wheel interactions. Let me get bazooka and test it. But I think I just need to convert that function to the settings getvalue.
